[[build.buildpacks]]
  # Use the explicit, full URI for the apt buildpack
  uri = "docker.io/googlecloudplatform/buildpacks:google.utils.apt"

[[build.buildpacks]]
  uri = "google.nodejs.runtime"

[[build.buildpacks]]
  uri = "google.nodejs.npm"